# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='total_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
