# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
