# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 19:58
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, null=True, upload_to=api.models.get_UserProfile_avatar_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
