# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='inital_price',
            field=models.DecimalField(decimal_places=2, default=34, max_digits=8),
            preserve_default=False,
        ),
    ]
