# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170208_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
